# Copyright 2020 Tomas Brabec
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import RstWriterTestUtils
import docutils
import docutils.core

def suite():
    s = RstWriterTestUtils.PublishTestSuite(writer_name='docutils-rstwriter')
    s.generateTests(totest)
    return s

totest = {}

totest['footnotes'] = [
["""\
.. [1] This is a footnote.
""",
"""\
.. [1] This is a footnote.
"""],
["""\
.. [1] This is a footnote
   on multiple lines.
""",
"""\
.. [1] This is a footnote
   on multiple lines.
"""],
["""\
.. [1] This is a footnote
     on multiple lines with more space.

.. [2] This is a footnote
  on multiple lines with less space.
""",
"""\
.. [1] This is a footnote
   on multiple lines with more space.
.. [2] This is a footnote
   on multiple lines with less space.
"""],
["""\
.. [1]
   This is a footnote on multiple lines
   whose block starts on line 2.
""",
"""\
.. [1] This is a footnote on multiple lines
   whose block starts on line 2.
"""],
["""\
.. [1]

That was an empty footnote.
""",
"""\
.. [1]

That was an empty footnote.
"""],
["""\
.. [1]
No blank line.
""",
"""\
.. [1]

No blank line.
"""],
]

totest['auto_numbered_footnotes'] = [
#TODO ["""\
#TODO [#]_ is the first auto-numbered footnote reference.
#TODO [#]_ is the second auto-numbered footnote reference.
#TODO 
#TODO .. [#] Auto-numbered footnote 1.
#TODO .. [#] Auto-numbered footnote 2.
#TODO .. [#] Auto-numbered footnote 3.
#TODO 
#TODO [#]_ is the third auto-numbered footnote reference.
#TODO """,
#TODO """\
#TODO <document source="test data">
#TODO     <paragraph>
#TODO         <footnote_reference auto="1" ids="id1">
#TODO          is the first auto-numbered footnote reference.
#TODO         <footnote_reference auto="1" ids="id2">
#TODO          is the second auto-numbered footnote reference.
#TODO     <footnote auto="1" ids="id3">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 1.
#TODO     <footnote auto="1" ids="id4">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 2.
#TODO     <footnote auto="1" ids="id5">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 3.
#TODO     <paragraph>
#TODO         <footnote_reference auto="1" ids="id6">
#TODO          is the third auto-numbered footnote reference.
#TODO """],
#TODO ["""\
#TODO [#third]_ is a reference to the third auto-numbered footnote.
#TODO 
#TODO .. [#first] First auto-numbered footnote.
#TODO .. [#second] Second auto-numbered footnote.
#TODO .. [#third] Third auto-numbered footnote.
#TODO 
#TODO [#second]_ is a reference to the second auto-numbered footnote.
#TODO [#first]_ is a reference to the first auto-numbered footnote.
#TODO [#third]_ is another reference to the third auto-numbered footnote.
#TODO 
#TODO Here are some internal cross-references to the targets generated by
#TODO the footnotes: first_, second_, third_.
#TODO """,
#TODO """\
#TODO <document source="test data">
#TODO     <paragraph>
#TODO         <footnote_reference auto="1" ids="id1" refname="third">
#TODO          is a reference to the third auto-numbered footnote.
#TODO     <footnote auto="1" ids="first" names="first">
#TODO         <paragraph>
#TODO             First auto-numbered footnote.
#TODO     <footnote auto="1" ids="second" names="second">
#TODO         <paragraph>
#TODO             Second auto-numbered footnote.
#TODO     <footnote auto="1" ids="third" names="third">
#TODO         <paragraph>
#TODO             Third auto-numbered footnote.
#TODO     <paragraph>
#TODO         <footnote_reference auto="1" ids="id2" refname="second">
#TODO          is a reference to the second auto-numbered footnote.
#TODO         <footnote_reference auto="1" ids="id3" refname="first">
#TODO          is a reference to the first auto-numbered footnote.
#TODO         <footnote_reference auto="1" ids="id4" refname="third">
#TODO          is another reference to the third auto-numbered footnote.
#TODO     <paragraph>
#TODO         Here are some internal cross-references to the targets generated by
#TODO         the footnotes: \n\
#TODO         <reference name="first" refname="first">
#TODO             first
#TODO         , \n\
#TODO         <reference name="second" refname="second">
#TODO             second
#TODO         , \n\
#TODO         <reference name="third" refname="third">
#TODO             third
#TODO         .
#TODO """],
#TODO ["""\
#TODO Mixed anonymous and labelled auto-numbered footnotes:
#TODO 
#TODO [#four]_ should be 4, [#]_ should be 1,
#TODO [#]_ should be 3, [#]_ is one too many,
#TODO [#two]_ should be 2, and [#six]_ doesn't exist.
#TODO 
#TODO .. [#] Auto-numbered footnote 1.
#TODO .. [#two] Auto-numbered footnote 2.
#TODO .. [#] Auto-numbered footnote 3.
#TODO .. [#four] Auto-numbered footnote 4.
#TODO .. [#five] Auto-numbered footnote 5.
#TODO .. [#five] Auto-numbered footnote 5 again (duplicate).
#TODO """,
#TODO """\
#TODO <document source="test data">
#TODO     <paragraph>
#TODO         Mixed anonymous and labelled auto-numbered footnotes:
#TODO     <paragraph>
#TODO         <footnote_reference auto="1" ids="id1" refname="four">
#TODO          should be 4, \n\
#TODO         <footnote_reference auto="1" ids="id2">
#TODO          should be 1,
#TODO         <footnote_reference auto="1" ids="id3">
#TODO          should be 3, \n\
#TODO         <footnote_reference auto="1" ids="id4">
#TODO          is one too many,
#TODO         <footnote_reference auto="1" ids="id5" refname="two">
#TODO          should be 2, and \n\
#TODO         <footnote_reference auto="1" ids="id6" refname="six">
#TODO          doesn't exist.
#TODO     <footnote auto="1" ids="id7">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 1.
#TODO     <footnote auto="1" ids="two" names="two">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 2.
#TODO     <footnote auto="1" ids="id8">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 3.
#TODO     <footnote auto="1" ids="four" names="four">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 4.
#TODO     <footnote auto="1" dupnames="five" ids="five">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 5.
#TODO     <footnote auto="1" dupnames="five" ids="id9">
#TODO         <system_message backrefs="id9" level="2" line="12" source="test data" type="WARNING">
#TODO             <paragraph>
#TODO                 Duplicate explicit target name: "five".
#TODO         <paragraph>
#TODO             Auto-numbered footnote 5 again (duplicate).
#TODO """],
#TODO ["""\
#TODO Mixed manually-numbered, anonymous auto-numbered,
#TODO and labelled auto-numbered footnotes:
#TODO 
#TODO [#four]_ should be 4, [#]_ should be 2,
#TODO [1]_ is 1, [3]_ is 3,
#TODO [#]_ should be 6, [#]_ is one too many,
#TODO [#five]_ should be 5, and [#six]_ doesn't exist.
#TODO 
#TODO .. [1] Manually-numbered footnote 1.
#TODO .. [#] Auto-numbered footnote 2.
#TODO .. [#four] Auto-numbered footnote 4.
#TODO .. [3] Manually-numbered footnote 3
#TODO .. [#five] Auto-numbered footnote 5.
#TODO .. [#five] Auto-numbered footnote 5 again (duplicate).
#TODO .. [#] Auto-numbered footnote 6.
#TODO """,
#TODO """\
#TODO <document source="test data">
#TODO     <paragraph>
#TODO         Mixed manually-numbered, anonymous auto-numbered,
#TODO         and labelled auto-numbered footnotes:
#TODO     <paragraph>
#TODO         <footnote_reference auto="1" ids="id1" refname="four">
#TODO          should be 4, \n\
#TODO         <footnote_reference auto="1" ids="id2">
#TODO          should be 2,
#TODO         <footnote_reference ids="id3" refname="1">
#TODO             1
#TODO          is 1, \n\
#TODO         <footnote_reference ids="id4" refname="3">
#TODO             3
#TODO          is 3,
#TODO         <footnote_reference auto="1" ids="id5">
#TODO          should be 6, \n\
#TODO         <footnote_reference auto="1" ids="id6">
#TODO          is one too many,
#TODO         <footnote_reference auto="1" ids="id7" refname="five">
#TODO          should be 5, and \n\
#TODO         <footnote_reference auto="1" ids="id8" refname="six">
#TODO          doesn't exist.
#TODO     <footnote ids="id9" names="1">
#TODO         <label>
#TODO             1
#TODO         <paragraph>
#TODO             Manually-numbered footnote 1.
#TODO     <footnote auto="1" ids="id10">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 2.
#TODO     <footnote auto="1" ids="four" names="four">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 4.
#TODO     <footnote ids="id11" names="3">
#TODO         <label>
#TODO             3
#TODO         <paragraph>
#TODO             Manually-numbered footnote 3
#TODO     <footnote auto="1" dupnames="five" ids="five">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 5.
#TODO     <footnote auto="1" dupnames="five" ids="id12">
#TODO         <system_message backrefs="id12" level="2" line="14" source="test data" type="WARNING">
#TODO             <paragraph>
#TODO                 Duplicate explicit target name: "five".
#TODO         <paragraph>
#TODO             Auto-numbered footnote 5 again (duplicate).
#TODO     <footnote auto="1" ids="id13">
#TODO         <paragraph>
#TODO             Auto-numbered footnote 6.
#TODO """],
]

totest['auto_symbol_footnotes'] = [
["""\
.. [*] This is an auto-symbol footnote.
""",
"""\
.. [*] This is an auto-symbol footnote.
"""],
]


def load_tests(loader, tests, pattern):
    return suite()

if __name__ == '__main__':
    import unittest
    unittest.main(defaultTest='suite')
